kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oracle-sa-anyuid-rolebinding
{{- include "oracle-db-labels" . | indent 2 }}
subjects:
  - kind: ServiceAccount
    name: oracle-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
